project_id = "nxeorbwqsovybfttemrw"

[functions.ask]
verify_jwt = false

[functions.embed-sections]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.realtime-voice]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.realtime-search]
verify_jwt = false

[functions.ask-product]
verify_jwt = false

[functions.embed-products]
verify_jwt = false

[functions.ingest]
verify_jwt = false

[functions.course-tutor]
verify_jwt = false

[functions.course-assess]
verify_jwt = false

[functions.course-evaluate]
verify_jwt = false

[functions.course-quiz-generate]
verify_jwt = false

[functions.tts]
verify_jwt = false

[functions.ingest-file]
verify_jwt = false

[functions.ingest-vision]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.ask-form]
verify_jwt = false
